import { ClipItem, VideoMetadata } from "../types";

export const SAMPLE_VIDEOS: VideoMetadata[] = [
  {
    id: "tech_trends",
    title: "O Futuro da Inteligência Artificial (Entrevista Guru)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", // fallback, typically replaced by canvas visual synth
    description: "Um especialista em tecnologia explicando de forma entusiasmada as novas revoluções no mercado de trabalho e o poder da programação com IA.",
    duration: 35,
    transcript: `O mercado de tecnologia mudou completamente. Hoje em dia, quem sabe utilizar ferramentas de Inteligência Artificial para acelerar o seu fluxo de desenvolvimento tem uma vantagem competitiva absurda. Não se trata de ser substituído pela IA, mas sim de ser substituído por alguém que sabe usá-la melhor do que você. O segredo é ter curiosidade, experimentar novas ideias todos os dias e criar soluções reais para problemas reais do mercado.`
  },
  {
    id: "motivation",
    title: "Mentalidade Inabalável (Influenciador de Sucesso)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    description: "Discurso motivacional de alta intensidade com pausas dramáticas e conselhos práticos para vencer a procrastinação cotidiana.",
    duration: 30,
    transcript: `O seu maior inimigo está refletido no espelho todas as manhãs. A procrastinação não é falta de tempo, é falta de prioridade e medo do fracasso. Pare de esperar as condições perfeitas para começar o seu projeto. A perfeição é uma ilusão que te paralisa. Dê o primeiro passo hoje, ajuste a rota no caminho e conquiste aquilo que você sempre sonhou.`
  },
  {
    id: "cooking",
    title: "A Receita Secreta do Cookie Perfeito (Ultra Rápido)",
    url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    description: "Roteiro gastronômico ultra-veloz, estilo Reels de culinária, cheio de humor e truques para deixar a receita crocante.",
    duration: 25,
    transcript: `Esqueça tudo o que você já te ensinaram sobre fazer cookies! O verdadeiro segredo que as padarias francesas escondem de você está na temperatura da manteiga. Manteiga marrom levemente tostada é o que dá aquele toque de nozes insano. Misture açúcar mascavo, chocolate 70% em gotas generosas e asse por exatos nove minutos. Fica crocante por fora e absurdamente macio por dentro!`
  }
];

export const PRESET_CLIPS_DATA: Record<string, ClipItem[]> = {
  tech_trends: [
    {
      title: "🤖 IA não vai te substituir (Mas quem souber usar vai!)",
      start: 0,
      end: 15,
      viralScore: 95,
      justification: "Gancho inicial fortíssimo atacando o medo do desemprego causado pela IA, gerando alto engajamento e compartilhamento imediato.",
      panningEvents: [
        { time: 0, offsetPercent: 0 },
        { time: 5, offsetPercent: -15 },
        { time: 10, offsetPercent: 20 },
        { time: 14, offsetPercent: 0 }
      ],
      subtitles: [
        { text: "O", start: 0.1, end: 0.3 },
        { text: "mercado", start: 0.3, end: 0.6 },
        { text: "de", start: 0.6, end: 0.8 },
        { text: "tecnologia", start: 0.8, end: 1.2 },
        { text: "mudou", start: 1.2, end: 1.5 },
        { text: "completamente.", start: 1.5, end: 1.9 },
        { text: "Hoje", start: 2.2, end: 2.5 },
        { text: "em", start: 2.5, end: 2.7 },
        { text: "dia,", start: 2.7, end: 2.9 },
        { text: "quem", start: 3.0, end: 3.2 },
        { text: "sabe", start: 3.2, end: 3.5 },
        { text: "utilizar", start: 3.5, end: 3.9 },
        { text: "Inteligência", start: 3.9, end: 4.4 },
        { text: "Artificial", start: 4.4, end: 4.9 },
        { text: "para", start: 4.9, end: 5.1 },
        { text: "acelerar", start: 5.1, end: 5.5 },
        { text: "o", start: 5.5, end: 5.7 },
        { text: "seu", start: 5.7, end: 5.9 },
        { text: "ritmo", start: 5.9, end: 6.2 },
        { text: "tem", start: 6.2, end: 6.4 },
        { text: "uma", start: 6.4, end: 6.6 },
        { text: "vantagem", start: 6.6, end: 7.1 },
        { text: "competitiva", start: 7.1, end: 7.7 },
        { text: "absurda.", start: 7.7, end: 8.2 },
        { text: "Não", start: 8.8, end: 9.1 },
        { text: "se", start: 9.1, end: 9.3 },
        { text: "trata", start: 9.3, end: 9.6 },
        { text: "de", start: 9.6, end: 9.8 },
        { text: "ser", start: 9.8, end: 10.1 },
        { text: "substituído", start: 10.1, end: 10.7 },
        { text: "pela", start: 10.7, end: 11.0 },
        { text: "IA,", start: 11.0, end: 11.4 },
        { text: "mas", start: 11.6, end: 11.8 },
        { text: "sim", start: 11.8, end: 12.1 },
        { text: "por", start: 12.1, end: 12.3 },
        { text: "alguém", start: 12.3, end: 12.7 },
        { text: "que", start: 12.7, end: 12.9 },
        { text: "sabe", start: 12.9, end: 13.2 },
        { text: "usar", start: 13.2, end: 13.5 },
        { text: "ela", start: 13.5, end: 13.8 },
        { text: "melhor", start: 13.8, end: 14.2 },
        { text: "que", start: 14.2, end: 14.4 },
        { text: "você.", start: 14.4, end: 14.9 }
      ]
    },
    {
      title: "💡 O segredo profissional para IA em 2026",
      start: 15,
      end: 34,
      viralScore: 89,
      justification: "Segmento focado em conselhos práticos de carreira e aplicação no mundo real, aumentando o salvamento de postagem no Instagram.",
      panningEvents: [
        { time: 15, offsetPercent: 5 },
        { time: 22, offsetPercent: -10 },
        { time: 30, offsetPercent: 0 }
      ],
      subtitles: [
        { text: "O", start: 15.1, end: 15.3 },
        { text: "segredo", start: 15.3, end: 15.8 },
        { text: "é", start: 15.8, end: 16.0 },
        { text: "ter", start: 16.0, end: 16.2 },
        { text: "curiosidade,", start: 16.2, end: 16.8 },
        { text: "experimentar", start: 17.0, end: 17.6 },
        { text: "novas", start: 17.6, end: 18.0 },
        { text: "ideias", start: 18.0, end: 18.4 },
        { text: "todos", start: 18.4, end: 18.7 },
        { text: "os", start: 18.7, end: 18.9 },
        { text: "dias", start: 18.9, end: 19.3 },
        { text: "e", start: 19.5, end: 19.7 },
        { text: "criar", start: 19.7, end: 20.1 },
        { text: "soluções", start: 20.1, end: 20.6 },
        { text: "reais", start: 20.6, end: 21.0 },
        { text: "para", start: 21.0, end: 21.2 },
        { text: "problemas", start: 21.2, end: 21.7 },
        { text: "reais", start: 21.7, end: 22.1 },
        { text: "do", start: 22.1, end: 22.3 },
        { text: "nosso", start: 22.3, end: 22.6 },
        { text: "mercado.", start: 22.6, end: 23.1 }
      ]
    }
  ],
  motivation: [
    {
      title: "🔥 O Inimigo Silencioso no Espelho cotidianamente",
      start: 0,
      end: 14,
      viralScore: 98,
      justification: "Frase de impacto inicial ('O seu maior inimigo está refletido no espelho') muito dramática que prende a atenção nos primeiros 3 segundos.",
      panningEvents: [
        { time: 0, offsetPercent: 0 },
        { time: 5, offsetPercent: 10 },
        { time: 10, offsetPercent: -10 }
      ],
      subtitles: [
        { text: "O", start: 0.1, end: 0.3 },
        { text: "seu", start: 0.3, end: 0.5 },
        { text: "maior", start: 0.5, end: 0.9 },
        { text: "inimigo", start: 0.9, end: 1.4 },
        { text: "está", start: 1.4, end: 1.7 },
        { text: "refletido", start: 1.7, end: 2.2 },
        { text: "no", start: 2.2, end: 2.4 },
        { text: "espelho", start: 2.4, end: 2.9 },
        { text: "todas", start: 3.1, end: 3.4 },
        { text: "as", start: 3.4, end: 3.5 },
        { text: "manhãs.", start: 3.5, end: 4.1 },
        { text: "A", start: 4.6, end: 4.8 },
        { text: "procrastinação", start: 4.8, end: 5.6 },
        { text: "não", start: 5.6, end: 5.9 },
        { text: "é", start: 5.9, end: 6.1 },
        { text: "falta", start: 6.1, end: 6.4 },
        { text: "de", start: 6.4, end: 6.6 },
        { text: "tempo,", start: 6.6, end: 7.0 },
        { text: "é", start: 7.4, end: 7.6 },
        { text: "falta", start: 7.6, end: 7.9 },
        { text: "de", start: 7.9, end: 8.1 },
        { text: "prioridade", start: 8.1, end: 8.8 },
        { text: "e", start: 9.0, end: 9.3 },
        { text: "medo", start: 9.3, end: 9.6 },
        { text: "do", start: 9.6, end: 9.8 },
        { text: "fracasso.", start: 9.8, end: 10.4 }
      ]
    },
    {
      title: "🚀 O mito das condições perfeitas para começar",
      start: 14,
      end: 29,
      viralScore: 92,
      justification: "Clímax motivacional forte chamando o usuário para a ação, perfeito para compartilhamento nos stories de motivação e empreendedorismo.",
      panningEvents: [
        { time: 14, offsetPercent: -5 },
        { time: 20, offsetPercent: 5 },
        { time: 25, offsetPercent: 0 }
      ],
      subtitles: [
        { text: "Pare", start: 14.1, end: 14.5 },
        { text: "de", start: 14.5, end: 14.7 },
        { text: "esperar", start: 14.7, end: 15.2 },
        { text: "as", start: 15.2, end: 15.4 },
        { text: "condições", start: 15.4, end: 15.9 },
        { text: "perfeitas", start: 15.9, end: 16.5 },
        { text: "para", start: 16.5, end: 16.8 },
        { text: "começar.", start: 16.8, end: 17.3 },
        { text: "A", start: 17.8, end: 18.0 },
        { text: "perfeição", start: 18.0, end: 18.6 },
        { text: "é", start: 18.6, end: 18.8 },
        { text: "uma", start: 18.8, end: 19.0 },
        { text: "ilusão", start: 19.0, end: 19.6 },
        { text: "que", start: 19.6, end: 19.8 },
        { text: "te", start: 19.8, end: 20.0 },
        { text: "paralisa.", start: 20.0, end: 20.6 },
        { text: "Dê", start: 21.0, end: 21.3 },
        { text: "o", start: 21.3, end: 21.5 },
        { text: "primeiro", start: 21.5, end: 21.9 },
        { text: "passo", start: 21.9, end: 22.3 },
        { text: "hoje,", start: 22.3, end: 22.8 },
        { text: "ajuste", start: 23.2, end: 23.7 },
        { text: "a", start: 23.7, end: 23.9 },
        { text: "rota", start: 23.9, end: 24.3 },
        { text: "no", start: 24.3, end: 24.5 },
        { text: "caminho", start: 24.5, end: 25.1 },
        { text: "e", start: 25.4, end: 25.6 },
        { text: "conquiste", start: 25.6, end: 26.2 },
        { text: "aquilo", start: 26.2, end: 26.6 },
        { text: "que", start: 26.6, end: 26.8 },
        { text: "você", start: 26.8, end: 27.1 },
        { text: "sempre", start: 27.1, end: 27.5 },
        { text: "sonhou.", start: 27.5, end: 28.2 }
      ]
    }
  ],
  cooking: [
    {
      title: "🍪 Cookie ultra crocante (O segredo das padarias)",
      start: 0,
      end: 24,
      viralScore: 97,
      justification: "Ritmo rápido acelerado com imagens mentais deliciosas e segredos de cozinha revelados, ideal para viralizar rapidamente no Reels/Shorts.",
      panningEvents: [
        { time: 0, offsetPercent: 15 },
        { time: 6, offsetPercent: -15 },
        { time: 12, offsetPercent: 0 },
        { time: 18, offsetPercent: 20 }
      ],
      subtitles: [
        { text: "Esqueça", start: 0.1, end: 0.5 },
        { text: "tudo", start: 0.5, end: 0.8 },
        { text: "o", start: 0.8, end: 0.9 },
        { text: "que", start: 0.9, end: 1.1 },
        { text: "te", start: 1.1, end: 1.2 },
        { text: "ensinaram", start: 1.2, end: 1.8 },
        { text: "sobre", start: 1.8, end: 2.1 },
        { text: "fazer", start: 2.1, end: 2.4 },
        { text: "cookies!", start: 2.4, end: 2.9 },
        { text: "O", start: 3.2, end: 3.4 },
        { text: "verdadeiro", start: 3.4, end: 3.9 },
        { text: "segredo", start: 3.9, end: 4.4 },
        { text: "que", start: 4.4, end: 4.6 },
        { text: "as", start: 4.6, end: 4.7 },
        { text: "padarias", start: 4.7, end: 5.2 },
        { text: "francesas", start: 5.2, end: 5.8 },
        { text: "escondem", start: 5.8, end: 6.3 },
        { text: "está", start: 6.3, end: 6.6 },
        { text: "na", start: 6.6, end: 6.8 },
        { text: "temperatura", start: 6.8, end: 7.4 },
        { text: "da", start: 7.4, end: 7.6 },
        { text: "manteiga.", start: 7.6, end: 8.2 },
        { text: "Manteiga", start: 8.6, end: 9.1 },
        { text: "marrom", start: 9.1, end: 9.5 },
        { text: "levemente", start: 9.5, end: 10.0 },
        { text: "tostada", start: 10.0, end: 10.6 },
        { text: "é", start: 10.6, end: 10.8 },
        { text: "o", start: 10.8, end: 11.0 },
        { text: "que", start: 11.0, end: 11.2 },
        { text: "dá", start: 11.2, end: 11.4 },
        { text: "aquele", start: 11.4, end: 11.7 },
        { text: "gosto", start: 11.7, end: 12.0 },
        { text: "insano de nozes.", start: 12.0, end: 12.8 },
        { text: "Misture", start: 13.2, end: 13.7 },
        { text: "açúcar", start: 13.7, end: 14.1 },
        { text: "mascavo,", start: 14.1, end: 14.6 },
        { text: "gotas", start: 14.8, end: 15.2 },
        { text: "de", start: 15.2, end: 15.4 },
        { text: "chocolate", start: 15.4, end: 15.9 },
        { text: "sequeira", start: 15.9, end: 16.5 },
        { text: "e", start: 16.5, end: 16.7 },
        { text: "asse", start: 16.7, end: 17.1 },
        { text: "por", start: 17.1, end: 17.3 },
        { text: "exatos", start: 17.3, end: 17.7 },
        { text: "nove", start: 17.7, end: 18.0 },
        { text: "minutos.", start: 18.0, end: 18.5 },
        { text: "Fica", start: 18.9, end: 19.2 },
        { text: "crocante", start: 19.2, end: 19.7 },
        { text: "por", start: 19.7, end: 19.9 },
        { text: "fora", start: 19.9, end: 20.3 },
        { text: "e", start: 20.5, end: 20.7 },
        { text: "absurdamente", start: 20.7, end: 21.5 },
        { text: "cremoso", start: 21.5, end: 22.0 },
        { text: "por", start: 22.0, end: 22.2 },
        { text: "dentro!", start: 22.2, end: 22.8 }
      ]
    }
  ]
};
